In [4]:
#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
import numpy as np

v = np.arange(1, 11, 1)
print(f"vector: \n{v}")

vector: 
[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
#2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
import numpy as np

m = np.zeros((3, 3))
print(f"matrix: \n{m}")

matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
#3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
import numpy as np

m = np.random.randint(1, 11, size=(5, 5))
print(f"matrix: \n{m}")

matrix: 
[[ 6  1  4  4  8]
 [10  4  6  3  5]
 [ 8  7  9  9  2]
 [ 7  8  8  9  2]
 [ 6 10  9 10  5]]


In [32]:
#4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
import numpy as np

m = np.random.rand(4, 4)
print(f"matrix: \n{m}")

matrix: 
[[0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369]]


In [13]:
#5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
import numpy as np

v_1 = np.random.randint(1, 11, size=(5))
v_2 = np.random.randint(1, 11, size=(5))

print(f"v_1: \n{v_1}")
print(f"v_2: \n{v_2}")

plus = v_1 + v_2
print(f"plus: \n{plus}")
minus = v_1 - v_2
print(f"minus: \n{minus}")
multipl = v_1 * v_2
print(f"multipl: \n{multipl}")

v_1: 
[6 8 9 2 6]
v_2: 
[ 2  3 10  2  5]
plus: 
[ 8 11 19  4 11]
minus: 
[ 4  5 -1  0  1]
multipl: 
[12 24 90  4 30]


In [12]:
#6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
import numpy as np

v_1 = np.random.randint(1, 7, size=(7))
v_2 = np.random.randint(1, 7, size=(7))

print(f"v_1: \n{v_1}")
print(f"v_2: \n{v_2}")

s_m = np.dot(v_1, v_2)
print(f"s_m: \n{s_m}")

v_1: 
[6 1 4 3 6 3 5]
v_2: 
[6 1 2 1 2 5 4]
s_m: 
95


In [16]:
#7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
import numpy as np

m_1 = np.random.randint(1, 11, size=(2, 2))
m_2 = np.random.randint(1, 11, size=(2, 3))
s_m = np.dot(m_1, m_2)

print(f"m_1: \n{m_1}")
print(f"m_2: \n{m_2}")
print(f"s_m: \n{s_m}")

m_1: 
[[9 1]
 [3 5]]
m_2: 
[[10  8  8]
 [ 6  3  9]]
s_m: 
[[96 75 81]
 [60 39 69]]


In [30]:
#8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
import numpy as np

m = np.random.randint(1, 11, size=(3, 3))
m_inv = np.linalg.inv(m)

print(f"m: \n{m}")
print(f"m_inv: \n{(m_inv)}")

m: 
[[ 1  2  8]
 [ 6  6 10]
 [ 8  3  2]]
m_inv: 
[[ 0.14754098 -0.16393443  0.2295082 ]
 [-0.55737705  0.50819672 -0.31147541]
 [ 0.24590164 -0.10655738  0.04918033]]


In [32]:
#9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
import numpy as np

m = np.random.rand(4, 4)
m_T = m.T

print(f"matrix: \n{m}")
print(f"matrix_trans: \n{m_T}")


matrix: 
[[0.10819415 0.58944759 0.25189195 0.79807194]
 [0.09648149 0.85157351 0.41815762 0.1500135 ]
 [0.49849609 0.57328258 0.22649723 0.89449032]
 [0.62018823 0.14835436 0.43466419 0.81234021]]
matrix_trans: 
[[0.10819415 0.09648149 0.49849609 0.62018823]
 [0.58944759 0.85157351 0.57328258 0.14835436]
 [0.25189195 0.41815762 0.22649723 0.43466419]
 [0.79807194 0.1500135  0.89449032 0.81234021]]


In [33]:
#10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
import numpy as np

m = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=(4))
res = np.dot(m, v)

print(f"m_1: \n{m}")
print(f"m_2: \n{v}")
print(f"res: \n{res}")


m_1: 
[[ 5  3 10  3]
 [ 1  4  6  4]
 [ 6 10  2  1]]
m_2: 
[2 1 2 3]
res: 
[42 30 29]


In [35]:
#11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
import numpy as np

m = np.random.random((2, 2))
v = np.random.random((2))
res = np.dot(m, v)

print(f"m_1: \n{m}")
print(f"m_2: \n{v}")
print(f"res: \n{res}")

m_1: 
[[0.9044754  0.01615238]
 [0.05198939 0.3550322 ]]
m_2: 
[0.7778351  0.03799138]
res: 
[0.70414636 0.05392733]


In [37]:
#12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
import numpy as np

m_1 = np.random.randint(1, 11, size=(2, 2))
m_2 = np.random.randint(1, 11, size=(2, 2))
s_m = m_1 * m_2

print(f"m_1: \n{m_1}")
print(f"m_2: \n{m_2}")
print(f"s_m: \n{s_m}")

m_1: 
[[6 4]
 [7 5]]
m_2: 
[[5 8]
 [1 8]]
s_m: 
[[30 32]
 [ 7 40]]


In [38]:
#13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
import numpy as np

m_1 = np.random.randint(1, 11, size=(2, 2))
m_2 = np.random.randint(1, 11, size=(2, 2))
s_m = np.dot(m_1, m_2)

print(f"m_1: \n{m_1}")
print(f"m_2: \n{m_2}")
print(f"s_m: \n{s_m}")

m_1: 
[[10  7]
 [10  2]]
m_2: 
[[3 1]
 [3 8]]
s_m: 
[[51 66]
 [36 26]]


In [42]:
#14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
import numpy as np

m = np.random.randint(1, 101, size=(5, 5))
sum = np.sum(m)

print(f"m: \n{m}")
print(f"sum: \n{sum}")

m: 
[[ 85  96 100  92  13]
 [ 95  13  28  48  70]
 [ 43  60  96  29  64]
 [  8  22  80  94  45]
 [  7   6  45  64  41]]
sum: 
1344


In [44]:
#15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
m_1 = np.random.randint(1, 11, size=(4, 4))
m_2 = np.random.randint(1, 11, size=(4, 4))
minus = m_1 - m_2

print(f"m_1: \n{m_1}")
print(f"m_2: \n{m_2}")
print(f"minus: \n{minus}")


m_1: 
[[ 4  9  7  5]
 [ 1  8  7  1]
 [ 4  5  5  4]
 [10  4  6 10]]
m_2: 
[[ 6  6  9 10]
 [ 3  6  1  4]
 [ 5  3  3  4]
 [ 7  7 10  5]]
minus: 
[[-2  3 -2 -5]
 [-2  2  6 -3]
 [-1  2  2  0]
 [ 3 -3 -4  5]]


In [7]:
#16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
import numpy as np

m = np.random.random((3, 3))
sum = np.sum(m, axis=1)
v_sum = sum[:, np.newaxis]

print(f"m: \n{m}")
print(f"sum: \n{v_sum}")

m: 
[[0.38672827 0.73674098 0.72809466]
 [0.99981203 0.22668673 0.60815245]
 [0.43138777 0.34870638 0.13699731]]
sum: 
[[1.85156391]
 [1.83465121]
 [0.91709147]]


In [54]:
#17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
import numpy as np

m = np.random.randint(1, 20, size=(3, 4))

sq = np.square(m)

print(f"m: \n{m}")
print(f"sq: \n{sq}")

m: 
[[15  5 16  3]
 [12 18 12 18]
 [17  4 13  5]]
sq: 
[[225  25 256   9]
 [144 324 144 324]
 [289  16 169  25]]
